"""Chenge function delete to Brand synonyms

Revision ID: 102fc3bf7eb3
Revises: ceb8b4924fce
Create Date: 2024-08-15 20:38:46.898985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102fc3bf7eb3'
down_revision: Union[str, None] = 'ceb8b4924fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_brand_synonyms_v2', 'brand_synonyms', type_='unique')
    op.create_unique_constraint('unique_brand_synonyms_v3', 'brand_synonyms', ['brand_id', 'synonym_id'])
    op.drop_constraint('brand_synonyms_brand_id_fkey', 'brand_synonyms', type_='foreignkey')
    op.drop_constraint('brand_synonyms_synonym_id_fkey', 'brand_synonyms', type_='foreignkey')
    op.create_foreign_key(None, 'brand_synonyms', 'brand', ['brand_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'brand_synonyms', 'brand', ['synonym_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand_synonyms', type_='foreignkey')
    op.drop_constraint(None, 'brand_synonyms', type_='foreignkey')
    op.create_foreign_key('brand_synonyms_synonym_id_fkey', 'brand_synonyms', 'brand', ['synonym_id'], ['id'])
    op.create_foreign_key('brand_synonyms_brand_id_fkey', 'brand_synonyms', 'brand', ['brand_id'], ['id'])
    op.drop_constraint('unique_brand_synonyms_v3', 'brand_synonyms', type_='unique')
    op.create_unique_constraint('unique_brand_synonyms_v2', 'brand_synonyms', ['brand_id', 'synonym_id'])
    # ### end Alembic commands ###
