"""Add providerabbreviation model

Revision ID: 14e6942a049a
Revises: fd57968e0964
Create Date: 2025-06-15 20:47:50.222535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e6942a049a'
down_revision: Union[str, None] = 'fd57968e0964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providerabbreviation',
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_unique_constraint('unique_autopart_category', 'autopart_category_association', ['autopart_id', 'category_id'])
    op.create_unique_constraint('unique_brand_synonyms', 'brand_synonyms', ['brand_id', 'synonym_id'])
    op.add_column('provider', sa.Column('is_virtual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'is_virtual')
    op.drop_constraint('unique_brand_synonyms', 'brand_synonyms', type_='unique')
    op.drop_constraint('unique_autopart_category', 'autopart_category_association', type_='unique')
    op.drop_table('providerabbreviation')
    # ### end Alembic commands ###
