"""Add min_delivery_day max_delivery_day brand_name in model AutoPartRestockDecisionSupplier

Revision ID: 16445dd39d1a
Revises: cd4e85e3fbfd
Create Date: 2025-08-01 14:26:38.931005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16445dd39d1a'
down_revision: Union[str, None] = 'cd4e85e3fbfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autopartrestockdecisionsupplier', sa.Column('brand_name', sa.String(), nullable=True))
    op.add_column('autopartrestockdecisionsupplier', sa.Column('min_delivery_day', sa.Integer(), nullable=True))
    op.add_column('autopartrestockdecisionsupplier', sa.Column('max_delivery_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autopartrestockdecisionsupplier', 'max_delivery_day')
    op.drop_column('autopartrestockdecisionsupplier', 'min_delivery_day')
    op.drop_column('autopartrestockdecisionsupplier', 'brand_name')
    # ### end Alembic commands ###
