"""Add Status

Revision ID: 16e4501fa957
Revises: 396a325da0ab
Create Date: 2025-07-25 17:05:00.364217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e4501fa957'
down_revision: Union[str, None] = '396a325da0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_autopart_category', 'autopart_category_association', ['autopart_id', 'category_id'])
    op.add_column('autopartrestockdecision', sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'FULFILLED', 'CANCELLED', name='type_restock_decision_status'), nullable=True))
    op.add_column('autopartrestockdecisionsupplier', sa.Column('status', sa.Enum('NEW', 'SEND', 'CONFIRMED', 'REJECTED', 'FULFILLED', 'ERROR', name='type_supplier_decision_status'), nullable=True))
    op.add_column('autopartrestockdecisionsupplier', sa.Column('send_method', sa.Enum('API', 'MAIL', name='type_send_method'), nullable=True))
    op.add_column('autopartrestockdecisionsupplier', sa.Column('send_date', sa.DateTime(), nullable=True))
    op.create_unique_constraint('unique_brand_synonyms', 'brand_synonyms', ['brand_id', 'synonym_id'])
    op.add_column('orderitem', sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'ARRIVED', 'CANCELLED', 'ERROR', name='type_order_item_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderitem', 'status')
    op.drop_constraint('unique_brand_synonyms', 'brand_synonyms', type_='unique')
    op.drop_column('autopartrestockdecisionsupplier', 'send_date')
    op.drop_column('autopartrestockdecisionsupplier', 'send_method')
    op.drop_column('autopartrestockdecisionsupplier', 'status')
    op.drop_column('autopartrestockdecision', 'status')
    op.drop_constraint('unique_autopart_category', 'autopart_category_association', type_='unique')
    # ### end Alembic commands ###
