"""Initial clean schema

Revision ID: 1b9ceff29846
Revises: 
Create Date: 2024-12-22 11:27:54.671543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9ceff29846'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=1056), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=1056), nullable=True),
    sa.Column('main_brand', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("name ~ '^[a-zA-Z0-9]+(?:[ -]?[a-zA-Z0-9]+)*$'", name='check_name_brand'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type_prices', sa.Enum('WHOLESALE', 'RETAIL', name='type_prices'), nullable=True),
    sa.Column('email_contact', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_client_email_contact'), 'client', ['email_contact'], unique=True)
    op.create_table('storagelocation',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("name ~ '^[A-Z0-9 ]+$'", name='latin_characters_only'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('autopart',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('oem_number', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('purchase_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('retail_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('wholesale_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('multiplicity', sa.Integer(), nullable=True),
    sa.Column('minimum_balance', sa.Integer(), nullable=True),
    sa.Column('min_balance_auto', sa.Boolean(), nullable=True),
    sa.Column('min_balance_user', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('height > 0', name='check_height_positive'),
    sa.CheckConstraint('length > 0', name='check_length_positive'),
    sa.CheckConstraint('purchase_price >= 0', name='check_purchase_price_non_negative'),
    sa.CheckConstraint('retail_price >= 0', name='check_retail_price_non_negative'),
    sa.CheckConstraint('weight > 0', name='check_weight_positive'),
    sa.CheckConstraint('wholesale_price >= 0', name='check_wholesale_price_non_negative'),
    sa.CheckConstraint('width > 0', name='check_width_positive'),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('brand_id', 'oem_number', name='uq_brand_oem_number')
    )
    op.create_index(op.f('ix_autopart_oem_number'), 'autopart', ['oem_number'], unique=False)
    op.create_table('brand_synonyms',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('synonym_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['synonym_id'], ['brand.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('brand_id', 'synonym_id'),
    sa.UniqueConstraint('brand_id', 'synonym_id', name='unique_brand_synonyms')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_outgoing_price', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_customer_email_outgoing_price'), 'customer', ['email_outgoing_price'], unique=True)
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_incoming_price', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_provider_email_incoming_price'), 'provider', ['email_incoming_price'], unique=True)
    op.create_table('autopart_category_association',
    sa.Column('autopart_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('autopart_id', 'category_id'),
    sa.UniqueConstraint('autopart_id', 'category_id', name='unique_autopart_category')
    )
    op.create_table('autopart_storage_association',
    sa.Column('autopart_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storagelocation.id'], ),
    sa.UniqueConstraint('autopart_id', 'storage_location_id', name='unique_autopart_storage_location')
    )
    op.create_table('customerpricelist',
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customerpricelistconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('general_markup', sa.Float(), nullable=True),
    sa.Column('own_price_list_markup', sa.Float(), nullable=True),
    sa.Column('third_party_markup', sa.Float(), nullable=True),
    sa.Column('individual_markups', sa.JSON(), nullable=True),
    sa.Column('brand_filters', sa.JSON(), nullable=True),
    sa.Column('category_filter', sa.JSON(), nullable=True),
    sa.Column('price_intervals', sa.JSON(), nullable=True),
    sa.Column('position_filters', sa.JSON(), nullable=True),
    sa.Column('supplier_quantity_filters', sa.JSON(), nullable=True),
    sa.Column('additional_filters', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('photo',
    sa.Column('url', sa.String(length=1056), nullable=False),
    sa.Column('autopart_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url', 'autopart_id', name='unique_photo')
    )
    op.create_table('pricelist',
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providerlastemailuid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('last_uid', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id', 'provider_id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_table('providerpricelistconfig',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('oem_col', sa.Integer(), nullable=False),
    sa.Column('name_col', sa.Integer(), nullable=True),
    sa.Column('brand_col', sa.Integer(), nullable=True),
    sa.Column('qty_col', sa.Integer(), nullable=False),
    sa.Column('price_col', sa.Integer(), nullable=False),
    sa.Column('name_price', sa.String(), nullable=True),
    sa.Column('name_mail', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    op.create_table('customerpricelistautopartassociation',
    sa.Column('customerpricelist_id', sa.Integer(), nullable=False),
    sa.Column('autopart_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.ForeignKeyConstraint(['customerpricelist_id'], ['customerpricelist.id'], ),
    sa.PrimaryKeyConstraint('customerpricelist_id', 'autopart_id')
    )
    op.create_index('ix_customer_price_list_autopart_id', 'customerpricelistautopartassociation', ['autopart_id'], unique=False)
    op.create_index('ix_customer_price_list_customerpricelist_id', 'customerpricelistautopartassociation', ['customerpricelist_id'], unique=False)
    op.create_table('pricelistautopartassociation',
    sa.Column('pricelist_id', sa.Integer(), nullable=False),
    sa.Column('autopart_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.ForeignKeyConstraint(['pricelist_id'], ['pricelist.id'], ),
    sa.PrimaryKeyConstraint('pricelist_id', 'autopart_id')
    )
    op.create_index('ix_price_list_autopart_id', 'pricelistautopartassociation', ['autopart_id'], unique=False)
    op.create_index('ix_price_list_pricelist_id', 'pricelistautopartassociation', ['pricelist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_list_pricelist_id', table_name='pricelistautopartassociation')
    op.drop_index('ix_price_list_autopart_id', table_name='pricelistautopartassociation')
    op.drop_table('pricelistautopartassociation')
    op.drop_index('ix_customer_price_list_customerpricelist_id', table_name='customerpricelistautopartassociation')
    op.drop_index('ix_customer_price_list_autopart_id', table_name='customerpricelistautopartassociation')
    op.drop_table('customerpricelistautopartassociation')
    op.drop_table('providerpricelistconfig')
    op.drop_table('providerlastemailuid')
    op.drop_table('pricelist')
    op.drop_table('photo')
    op.drop_table('customerpricelistconfig')
    op.drop_table('customerpricelist')
    op.drop_table('autopart_storage_association')
    op.drop_table('autopart_category_association')
    op.drop_index(op.f('ix_provider_email_incoming_price'), table_name='provider')
    op.drop_table('provider')
    op.drop_index(op.f('ix_customer_email_outgoing_price'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('brand_synonyms')
    op.drop_index(op.f('ix_autopart_oem_number'), table_name='autopart')
    op.drop_table('autopart')
    op.drop_table('storagelocation')
    op.drop_index(op.f('ix_client_email_contact'), table_name='client')
    op.drop_table('client')
    op.drop_table('category')
    op.drop_table('brand')
    # ### end Alembic commands ###
