"""Add column for ProviderPriceListConfig

Revision ID: 1db1fdbcb8de
Revises: 85607d9739ca
Create Date: 2024-11-23 21:44:35.570803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db1fdbcb8de'
down_revision: Union[str, None] = '85607d9739ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providerpricelistconfig', sa.Column('name_price', sa.String(), nullable=True))
    op.add_column('providerpricelistconfig', sa.Column('name_mail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providerpricelistconfig', 'name_mail')
    op.drop_column('providerpricelistconfig', 'name_price')
    # ### end Alembic commands ###
