"""fix cross oem number and timezone

Revision ID: 2179bca37b49
Revises: a2f8afd6cdc9
Create Date: 2026-02-14 15:55:21.221242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2179bca37b49'
down_revision: Union[str, None] = 'a2f8afd6cdc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'autopartcross',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'source_autopart_id',
            sa.Integer(),
            sa.ForeignKey('autopart.id', ondelete='CASCADE'),
            nullable=False,
        ),
        sa.Column(
            'cross_brand_id',
            sa.Integer(),
            sa.ForeignKey('brand.id', ondelete='CASCADE'),
            nullable=False,
        ),
        sa.Column('cross_oem_number', sa.String(length=50), nullable=False),
        sa.Column(
            'cross_autopart_id',
            sa.Integer(),
            sa.ForeignKey('autopart.id', ondelete='SET NULL'),
            nullable=True,
        ),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.CheckConstraint(
            'source_autopart_id != cross_autopart_id',
            name='check_not_self_cross',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'source_autopart_id',
            'cross_brand_id',
            'cross_oem_number',
            name='uq_cross',
        ),
    )
    op.create_index(
        op.f('ix_autopartcross_source_autopart_id'),
        'autopartcross',
        ['source_autopart_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_autopartcross_cross_brand_id'),
        'autopartcross',
        ['cross_brand_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_autopartcross_cross_oem_number'),
        'autopartcross',
        ['cross_oem_number'],
        unique=False,
    )

    op.create_table(
        'autopartsubstitution',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'source_autopart_id',
            sa.Integer(),
            sa.ForeignKey('autopart.id', ondelete='CASCADE'),
            nullable=False,
        ),
        sa.Column(
            'substitution_brand_id',
            sa.Integer(),
            sa.ForeignKey('brand.id', ondelete='CASCADE'),
            nullable=False,
        ),
        sa.Column(
            'substitution_oem_number',
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('min_source_quantity', sa.Integer(), nullable=True),
        sa.Column('quantity_reduction', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column(
            'customer_config_id',
            sa.Integer(),
            sa.ForeignKey('customerpricelistconfig.id', ondelete='CASCADE'),
            nullable=True,
        ),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.CheckConstraint(
            'priority > 0',
            name='check_priority_positive',
        ),
        sa.CheckConstraint(
            'min_source_quantity >= 0',
            name='check_min_quantity_non_negative',
        ),
        sa.CheckConstraint(
            'quantity_reduction >= 0',
            name='check_reduction_non_negative',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'source_autopart_id',
            'substitution_brand_id',
            'substitution_oem_number',
            'customer_config_id',
            name='uq_substitution',
        ),
    )
    op.create_index(
        op.f('ix_autopartsubstitution_source_autopart_id'),
        'autopartsubstitution',
        ['source_autopart_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_autopartsubstitution_substitution_brand_id'),
        'autopartsubstitution',
        ['substitution_brand_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_autopartsubstitution_substitution_oem_number'),
        'autopartsubstitution',
        ['substitution_oem_number'],
        unique=False,
    )
    op.create_index(
        op.f('ix_autopartsubstitution_customer_config_id'),
        'autopartsubstitution',
        ['customer_config_id'],
        unique=False,
    )

    op.execute(
        """
        DO $$
        BEGIN
            ALTER TABLE autopart_category_association
            ADD CONSTRAINT unique_autopart_category UNIQUE (autopart_id, category_id);
        EXCEPTION
            WHEN duplicate_object THEN NULL;
            WHEN duplicate_table THEN NULL;
        END $$;
        """
    )
    op.alter_column('autopartpricehistory', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.execute(
        """
        DO $$
        BEGIN
            ALTER TABLE brand_synonyms
            ADD CONSTRAINT unique_brand_synonyms UNIQUE (brand_id, synonym_id);
        EXCEPTION
            WHEN duplicate_object THEN NULL;
            WHEN duplicate_table THEN NULL;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            ALTER TABLE brand_synonyms
            DROP CONSTRAINT unique_brand_synonyms;
        EXCEPTION
            WHEN undefined_object THEN NULL;
        END $$;
        """
    )
    op.alter_column('autopartpricehistory', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.execute(
        """
        DO $$
        BEGIN
            ALTER TABLE autopart_category_association
            DROP CONSTRAINT unique_autopart_category;
        EXCEPTION
            WHEN undefined_object THEN NULL;
        END $$;
        """
    )

    op.drop_index(
        op.f('ix_autopartsubstitution_customer_config_id'),
        table_name='autopartsubstitution',
    )
    op.drop_index(
        op.f('ix_autopartsubstitution_substitution_oem_number'),
        table_name='autopartsubstitution',
    )
    op.drop_index(
        op.f('ix_autopartsubstitution_substitution_brand_id'),
        table_name='autopartsubstitution',
    )
    op.drop_index(
        op.f('ix_autopartsubstitution_source_autopart_id'),
        table_name='autopartsubstitution',
    )
    op.drop_table('autopartsubstitution')

    op.drop_index(
        op.f('ix_autopartcross_cross_oem_number'),
        table_name='autopartcross',
    )
    op.drop_index(
        op.f('ix_autopartcross_cross_brand_id'),
        table_name='autopartcross',
    )
    op.drop_index(
        op.f('ix_autopartcross_source_autopart_id'),
        table_name='autopartcross',
    )
    op.drop_table('autopartcross')
    # ### end Alembic commands ###
