"""Add relationship PriceList and Config

Revision ID: 22d3e2b9aac9
Revises: 2731df8a4738
Create Date: 2025-02-04 16:34:31.873295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d3e2b9aac9'
down_revision: Union[str, None] = '2731df8a4738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricelist', sa.Column('provider_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pricelist', 'providerpricelistconfig', ['provider_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pricelist', type_='foreignkey')
    op.drop_column('pricelist', 'provider_config_id')
    # ### end Alembic commands ###
