"""Barcode add in Autopart, and add some ckeck

Revision ID: 3861057a6ecd
Revises: 04da60905cf7
Create Date: 2024-09-04 15:23:50.486447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3861057a6ecd'
down_revision: Union[str, None] = '04da60905cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autopart', sa.Column('barcode', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'autopart', ['barcode'])
    op.drop_constraint('unique_brand_synonyms_v4', 'brand_synonyms', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_brand_synonyms_v4', 'brand_synonyms', ['brand_id', 'synonym_id'])
    op.drop_constraint(None, 'autopart', type_='unique')
    op.drop_column('autopart', 'barcode')
    # ### end Alembic commands ###
