"""Create tracking_uuid autopartrestock

Revision ID: 45f3c75242f6
Revises: edbc1498463f
Create Date: 2025-08-04 12:31:04.131438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f3c75242f6'
down_revision: Union[str, None] = 'edbc1498463f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_autopart_category', 'autopart_category_association', ['autopart_id', 'category_id'])
    op.add_column('autopartrestockdecisionsupplier', sa.Column('tracking_uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_autopartrestockdecisionsupplier_tracking_uuid'), 'autopartrestockdecisionsupplier', ['tracking_uuid'], unique=True)
    op.create_unique_constraint('unique_brand_synonyms', 'brand_synonyms', ['brand_id', 'synonym_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_brand_synonyms', 'brand_synonyms', type_='unique')
    op.drop_index(op.f('ix_autopartrestockdecisionsupplier_tracking_uuid'), table_name='autopartrestockdecisionsupplier')
    op.drop_column('autopartrestockdecisionsupplier', 'tracking_uuid')
    op.drop_constraint('unique_autopart_category', 'autopart_category_association', type_='unique')
    # ### end Alembic commands ###
