"""Change model CustomerPriceListConfig

Revision ID: 51e6113c540c
Revises: d44245e6aabd
Create Date: 2024-11-19 11:50:39.561871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e6113c540c'
down_revision: Union[str, None] = 'd44245e6aabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customerpricelistconfig', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('customerpricelistconfig_customer_id_key', 'customerpricelistconfig', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('customerpricelistconfig_customer_id_key', 'customerpricelistconfig', ['customer_id'])
    op.alter_column('customerpricelistconfig', 'customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
