"""Add min end max delivery for ProviderPriceListConfig

Revision ID: 5f9d313d9bca
Revises: 9c66dc053cff
Create Date: 2025-07-24 15:35:08.197000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9d313d9bca'
down_revision: Union[str, None] = '9c66dc053cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providerpricelistconfig', sa.Column('min_delivery_day', sa.Integer(), nullable=True, server_default='1'))
    op.add_column('providerpricelistconfig', sa.Column('max_delivery_day', sa.Integer(), nullable=True, server_default='2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providerpricelistconfig', 'max_delivery_day')
    op.drop_column('providerpricelistconfig', 'min_delivery_day')
    # ### end Alembic commands ###
