"""Add min end max delivery for ProviderPriceListConfig

Revision ID: 5f9d313d9bca
Revises: 9c66dc053cff
Create Date: 2025-07-24 15:35:08.197000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9d313d9bca'
down_revision: Union[str, None] = '9c66dc053cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_autopart_category', 'autopart_category_association', ['autopart_id', 'category_id'])
    op.create_unique_constraint('unique_brand_synonyms', 'brand_synonyms', ['brand_id', 'synonym_id'])
    op.add_column('providerpricelistconfig', sa.Column('min_delivery_day', sa.Integer(), nullable=True))
    op.add_column('providerpricelistconfig', sa.Column('max_delivery_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providerpricelistconfig', 'max_delivery_day')
    op.drop_column('providerpricelistconfig', 'min_delivery_day')
    op.drop_constraint('unique_brand_synonyms', 'brand_synonyms', type_='unique')
    op.drop_constraint('unique_autopart_category', 'autopart_category_association', type_='unique')
    # ### end Alembic commands ###
