"""Add table for history

Revision ID: 6a1f5aaec4f1
Revises: 1b9ceff29846
Create Date: 2025-01-22 13:13:59.608221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1f5aaec4f1'
down_revision: Union[str, None] = '1b9ceff29846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autopartpricehistory',
    sa.Column('autopart_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('pricelist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.ForeignKeyConstraint(['pricelist_id'], ['pricelist.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_autopart_price_history_autopart_provider_created_at', 'autopartpricehistory', ['autopart_id', 'provider_id', 'created_at'], unique=False)
    op.create_unique_constraint(None, 'customer', ['id'])
    op.create_unique_constraint(None, 'provider', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='unique')
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_index('idx_autopart_price_history_autopart_provider_created_at', table_name='autopartpricehistory')
    op.drop_table('autopartpricehistory')
    # ### end Alembic commands ###
