"""Add model for last UID email

Revision ID: 7de58656031b
Revises: 1db1fdbcb8de
Create Date: 2024-12-11 12:07:49.880937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de58656031b'
down_revision: Union[str, None] = '1db1fdbcb8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providerlastemailuid',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('last_uid', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('provider_id', 'id'),
    sa.UniqueConstraint('provider_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providerlastemailuid')
    # ### end Alembic commands ###
