"""Add chat messages table

Revision ID: 825b3630e27f
Revises: 852882513e8e
Create Date: 2026-02-01 10:36:38.651730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825b3630e27f'
down_revision: Union[str, None] = '852882513e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmessage',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=80), nullable=True),
    sa.Column('client_phone', sa.String(length=20), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('is_from_client', sa.Boolean(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_session_id'), 'chatmessage', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatmessage_session_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    # ### end Alembic commands ###
