"""Add id for ProviderLastEmailUID

Revision ID: 829afab775ef
Revises: 7de58656031b
Create Date: 2024-12-11 12:16:33.757123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '829afab775ef'
down_revision: Union[str, None] = '7de58656031b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('providerlastemailuid', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.execute("ALTER TABLE providerlastemailuid ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE providerlastemailuid ALTER COLUMN id DROP IDENTITY")

    op.alter_column('providerlastemailuid', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
