"""Add category end Storage

Revision ID: 87c207d08bc0
Revises: 3861057a6ecd
Create Date: 2024-09-15 20:34:46.151206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c207d08bc0'
down_revision: Union[str, None] = '3861057a6ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storagelocation',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("name ~ '^[A-Z0-9]+$'", name='latin_characters_only'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('autopart_category_association',
    sa.Column('autopart_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('autopart_id', 'category_id'),
    sa.UniqueConstraint('autopart_id', 'category_id', name='unique_autopart_category')
    )
    op.create_table('autopart_storage_association',
    sa.Column('autopart_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storagelocation.id'], ),
    sa.UniqueConstraint('autopart_id', 'storage_location_id', name='unique_autopart_storage_location')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autopart_storage_association')
    op.drop_table('autopart_category_association')
    op.drop_table('storagelocation')
    op.drop_table('category')
    # ### end Alembic commands ###
