"""Change AutoPartPriceHistory

Revision ID: a2f8afd6cdc9
Revises: 825b3630e27f
Create Date: 2026-02-14 15:08:23.643666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f8afd6cdc9'
down_revision: Union[str, None] = '825b3630e27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('autopartpricehistory_pricelist_id_fkey', 'autopartpricehistory', type_='foreignkey')
    op.create_index(op.f('ix_autopartpricehistory_pricelist_id'), 'autopartpricehistory', ['pricelist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_autopartpricehistory_pricelist_id'), table_name='autopartpricehistory')
    op.create_foreign_key('autopartpricehistory_pricelist_id_fkey', 'autopartpricehistory', 'pricelist', ['pricelist_id'], ['id'])
    # ### end Alembic commands ###
