"""Only autopart and brand

Revision ID: b125d65c004a
Revises: 5779db2be4c0
Create Date: 2024-05-05 22:59:24.554406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b125d65c004a'
down_revision: Union[str, None] = '5779db2be4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=1056), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=1056), nullable=True),
    sa.Column('main_brand', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint("name ~ '^[a-zA-Z0-9]+$'", name='check_name_brand'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('autopart',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('oem_number', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('purchase_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('retail_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('wholesale_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('multiplicity', sa.Integer(), nullable=True),
    sa.Column('minimum_balance', sa.Integer(), nullable=True),
    sa.Column('min_balance_auto', sa.Boolean(), nullable=True),
    sa.Column('min_balance_user', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'oem_number', name='uq_brand_oem_number')
    )
    op.create_index(op.f('ix_autopart_oem_number'), 'autopart', ['oem_number'], unique=False)
    op.create_table('brand_synonyms',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('synonym_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['synonym_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('brand_id', 'synonym_id'),
    sa.UniqueConstraint('brand_id', 'synonym_id', name='unique_brand_synonyms')
    )
    op.create_table('photo',
    sa.Column('url', sa.String(length=1056), nullable=False),
    sa.Column('autopart_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url', 'autopart_id', name='unique_photo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('brand_synonyms')
    op.drop_index(op.f('ix_autopart_oem_number'), table_name='autopart')
    op.drop_table('autopart')
    op.drop_table('brand')
    # ### end Alembic commands ###