"""Add hash_key and system_hash in OrderItem and AutoPartRestockDecisionSupplier

Revision ID: cd4e85e3fbfd
Revises: 16e4501fa957
Create Date: 2025-07-26 12:10:27.770473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4e85e3fbfd'
down_revision: Union[str, None] = '16e4501fa957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_autopart_category', 'autopart_category_association', ['autopart_id', 'category_id'])
    op.add_column('autopartrestockdecisionsupplier', sa.Column('hash_key', sa.String(length=255), nullable=True))
    op.add_column('autopartrestockdecisionsupplier', sa.Column('system_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_autopartrestockdecisionsupplier_hash_key'), 'autopartrestockdecisionsupplier', ['hash_key'], unique=False)
    op.create_index(op.f('ix_autopartrestockdecisionsupplier_system_hash'), 'autopartrestockdecisionsupplier', ['system_hash'], unique=False)
    op.create_unique_constraint('unique_brand_synonyms', 'brand_synonyms', ['brand_id', 'synonym_id'])
    op.add_column('orderitem', sa.Column('hash_key', sa.String(length=255), nullable=True))
    op.add_column('orderitem', sa.Column('system_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_orderitem_hash_key'), 'orderitem', ['hash_key'], unique=False)
    op.create_index(op.f('ix_orderitem_system_hash'), 'orderitem', ['system_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderitem_system_hash'), table_name='orderitem')
    op.drop_index(op.f('ix_orderitem_hash_key'), table_name='orderitem')
    op.drop_column('orderitem', 'system_hash')
    op.drop_column('orderitem', 'hash_key')
    op.drop_constraint('unique_brand_synonyms', 'brand_synonyms', type_='unique')
    op.drop_index(op.f('ix_autopartrestockdecisionsupplier_system_hash'), table_name='autopartrestockdecisionsupplier')
    op.drop_index(op.f('ix_autopartrestockdecisionsupplier_hash_key'), table_name='autopartrestockdecisionsupplier')
    op.drop_column('autopartrestockdecisionsupplier', 'system_hash')
    op.drop_column('autopartrestockdecisionsupplier', 'hash_key')
    op.drop_constraint('unique_autopart_category', 'autopart_category_association', type_='unique')
    # ### end Alembic commands ###
