"""Add cascade delete to Brand synonyms

Revision ID: ceb8b4924fce
Revises: 6ecf1f115624
Create Date: 2024-08-15 19:57:58.820620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb8b4924fce'
down_revision: Union[str, None] = '6ecf1f115624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_brand_synonyms_v2', 'brand_synonyms', ['brand_id', 'synonym_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_brand_synonyms_v2', 'brand_synonyms', type_='unique')
    # ### end Alembic commands ###
