"""Add CustomerPriceListConfig and CustomerPriceListAutoPartAssociation

Revision ID: d44245e6aabd
Revises: 42995af4f8b3
Create Date: 2024-11-18 14:19:09.481117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44245e6aabd'
down_revision: Union[str, None] = '42995af4f8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customerpricelistconfig',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('general_markup', sa.Float(), nullable=True),
    sa.Column('individual_markups', sa.JSON(), nullable=True),
    sa.Column('brand_filters', sa.JSON(), nullable=True),
    sa.Column('price_filters', sa.JSON(), nullable=True),
    sa.Column('additional_filters', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('customerpricelistautopartassociation',
    sa.Column('customerpricelist_id', sa.Integer(), nullable=False),
    sa.Column('autopart_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.ForeignKeyConstraint(['customerpricelist_id'], ['customerpricelist.id'], ),
    sa.PrimaryKeyConstraint('customerpricelist_id', 'autopart_id')
    )
    op.create_index('ix_customer_price_list_autopart_id', 'customerpricelistautopartassociation', ['autopart_id'], unique=False, if_not_exists=True)
    op.create_index('ix_customer_price_list_customerpricelist_id', 'customerpricelistautopartassociation', ['customerpricelist_id'], unique=False, if_not_exists=True)
    op.drop_index('ix_customer_price_list_autopart_id', table_name='customer_price_list_autopart_association')
    op.drop_index('ix_customer_price_list_customerpricelist_id', table_name='customer_price_list_autopart_association')
    op.drop_table('customer_price_list_autopart_association')
    op.create_index('ix_price_list_autopart_id', 'pricelistautopartassociation', ['autopart_id'], unique=False)
    op.create_index('ix_price_list_pricelist_id', 'pricelistautopartassociation', ['pricelist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_list_pricelist_id', table_name='pricelistautopartassociation')
    op.drop_index('ix_price_list_autopart_id', table_name='pricelistautopartassociation')
    op.create_table('customer_price_list_autopart_association',
    sa.Column('customerpricelist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('autopart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], name='customer_price_list_autopart_association_autopart_id_fkey'),
    sa.ForeignKeyConstraint(['customerpricelist_id'], ['customerpricelist.id'], name='customer_price_list_autopart_associat_customerpricelist_id_fkey'),
    sa.PrimaryKeyConstraint('customerpricelist_id', 'autopart_id', name='customer_price_list_autopart_association_pkey')
    )
    op.create_index('ix_customer_price_list_customerpricelist_id', 'customer_price_list_autopart_association', ['customerpricelist_id'], unique=False)
    op.create_index('ix_customer_price_list_autopart_id', 'customer_price_list_autopart_association', ['autopart_id'], unique=False)
    op.drop_index('ix_customer_price_list_customerpricelist_id', table_name='customerpricelistautopartassociation')
    op.drop_index('ix_customer_price_list_autopart_id', table_name='customerpricelistautopartassociation')
    op.drop_table('customerpricelistautopartassociation')
    op.drop_table('customerpricelistconfig')
    # ### end Alembic commands ###
