"""Change model Order and OrderItem

Revision ID: e3c62b8f1e4a
Revises: 5f9d313d9bca
Create Date: 2025-07-24 17:01:12.603186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c62b8f1e4a'
down_revision: Union[str, None] = '5f9d313d9bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_autopart_category', 'autopart_category_association', ['autopart_id', 'category_id'])
    op.create_unique_constraint('unique_brand_synonyms', 'brand_synonyms', ['brand_id', 'synonym_id'])
    op.add_column('order', sa.Column('order_number', sa.String(length=36), nullable=True))
    op.add_column('order', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'order', ['order_number'])
    op.add_column('orderitem', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orderitem', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orderitem', sa.Column('tracking_uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_orderitem_tracking_uuid'), 'orderitem', ['tracking_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderitem_tracking_uuid'), table_name='orderitem')
    op.drop_column('orderitem', 'tracking_uuid')
    op.drop_column('orderitem', 'updated_at')
    op.drop_column('orderitem', 'created_at')
    op.drop_constraint(None, 'order', type_='unique')
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'order_number')
    op.drop_constraint('unique_brand_synonyms', 'brand_synonyms', type_='unique')
    op.drop_constraint('unique_autopart_category', 'autopart_category_association', type_='unique')
    # ### end Alembic commands ###
