"""Change models

Revision ID: e76b25da6ed7
Revises: f4a73c25bac4
Create Date: 2024-11-15 12:02:24.874517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76b25da6ed7'
down_revision: Union[str, None] = 'f4a73c25bac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricelistautopartassociation',
    sa.Column('pricelist_id', sa.Integer(), nullable=False),
    sa.Column('autopart_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.ForeignKeyConstraint(['pricelist_id'], ['pricelist.id'], ),
    sa.PrimaryKeyConstraint('pricelist_id', 'autopart_id', 'id')
    )
    op.create_index('ix_price_list_autopart_id', 'pricelistautopartassociation', ['autopart_id'], unique=False, if_not_exists=True)
    op.create_index('ix_price_list_pricelist_id', 'pricelistautopartassociation', ['pricelist_id'], unique=False, if_not_exists=True)
    op.drop_index('ix_price_list_autopart_id', table_name='price_list_autopart_association')
    op.drop_index('ix_price_list_pricelist_id', table_name='price_list_autopart_association')
    op.drop_table('price_list_autopart_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_list_autopart_association',
    sa.Column('pricelist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('autopart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], name='price_list_autopart_association_autopart_id_fkey'),
    sa.ForeignKeyConstraint(['pricelist_id'], ['pricelist.id'], name='price_list_autopart_association_pricelist_id_fkey'),
    sa.PrimaryKeyConstraint('pricelist_id', 'autopart_id', name='price_list_autopart_association_pkey')
    )
    op.create_index('ix_price_list_pricelist_id', 'price_list_autopart_association', ['pricelist_id'], unique=False)
    op.create_index('ix_price_list_autopart_id', 'price_list_autopart_association', ['autopart_id'], unique=False)
    op.drop_index('ix_price_list_pricelist_id', table_name='pricelistautopartassociation')
    op.drop_index('ix_price_list_autopart_id', table_name='pricelistautopartassociation')
    op.drop_table('pricelistautopartassociation')
    # ### end Alembic commands ###
