"""Create relationship order and autopartrestock

Revision ID: edbc1498463f
Revises: 16445dd39d1a
Create Date: 2025-08-03 21:37:19.162750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbc1498463f'
down_revision: Union[str, None] = '16445dd39d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('restock_supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orderitem', 'autopartrestockdecisionsupplier', ['restock_supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_column('orderitem', 'restock_supplier_id')
    # ### end Alembic commands ###
