"""Chenge CheckConstraint for brand

Revision ID: f031465ac9e8
Revises: 6eef4f3b5048
Create Date: 2024-05-29 15:17:21.528816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text


# revision identifiers, used by Alembic.
revision: str = 'f031465ac9e8'
down_revision: Union[str, None] = '6eef4f3b5048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_name_brand', 'brand', type_='check')
    op.create_check_constraint('check_name_brand', 'brand', text("name ~ '^[a-zA-Z0-9-]+$'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_name_brand', 'brand', type_='check')
    op.create_check_constraint('check_name_brand', 'brand', text("name ~ '^[a-zA-Z0-9]+$'"))    # ### end Alembic commands ###
