"""Add ProviderPriceListConfig

Revision ID: f4a73c25bac4
Revises: 4a5508391712
Create Date: 2024-11-14 11:03:07.994629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a73c25bac4'
down_revision: Union[str, None] = '4a5508391712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providerpricelistconfig',
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('oem_col', sa.Integer(), nullable=False),
    sa.Column('name_col', sa.Integer(), nullable=True),
    sa.Column('brand_col', sa.Integer(), nullable=True),
    sa.Column('qty_col', sa.Integer(), nullable=False),
    sa.Column('price_col', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('providerpricelistconfig')
    # ### end Alembic commands ###
