"""Add AutoPartRestockDecision

Revision ID: fd57968e0964
Revises: e42f7cd5e43a
Create Date: 2025-04-22 16:33:38.770621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd57968e0964'
down_revision: Union[str, None] = 'e42f7cd5e43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autopartrestockdecision',
    sa.Column('autopart_id', sa.Integer(), nullable=True),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autopart_id'], ['autopart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autopartrestockdecision_autopart_id'), 'autopartrestockdecision', ['autopart_id'], unique=False)
    op.create_table('autopartrestockdecisionsupplier',
    sa.Column('restock_decision_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restock_decision_id'], ['autopartrestockdecision.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autopartrestockdecisionsupplier')
    op.drop_index(op.f('ix_autopartrestockdecision_autopart_id'), table_name='autopartrestockdecision')
    op.drop_table('autopartrestockdecision')
    # ### end Alembic commands ###
