version: '3.8'
services:
  db:
    container_name: dz_db_dev
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    env_file:
      - ../../.env
    ports:
      - "5432:5432"

  web:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: dz_fastapi_dev
    restart: always
    volumes:
      - ../..:/app
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    depends_on:
      - db

volumes:
  postgres_data:
