services:
  frontend:
    build:
      context: ../../dz_frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000


  db:
    ports:
      - "5432:5432"

  web:
    build:
      context: ../..
      dockerfile: Dockerfile
