services:
  db:
    container_name: dz_db_dev
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    healthcheck:
      # Проверяем, доступна ли БД через pg_isready
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-postgres} -h 127.0.0.1 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  web:
    image: alexesma/dz_fastapi:latest
#    build:
#      context: ../..
#      dockerfile: Dockerfile
    container_name: dz_fastapi_dev
    restart: always
#    volumes:
#      - ../..:/app
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    depends_on:
      db:
        condition: service_healthy  # Запуск web только когда db здорова
    healthcheck:
      # Для healthcheck нужен эндпойнт в FastAPI, напр. "/health"
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
